task: train
experiment: hs.kan
save_dir: .experiments
accelerator: gpu
devices: [0]
resume: True
epochs: 5800
save_freq: 1
visualize_freq: 1

defaults:
  - model: hskan
  - data: cave-hsi
  - pipeline: default
  - _self_